                <table class="sub-data-table" cellpadding="0" cellspacing="0" border="0">
                    <tr>
                        <th colspan="4">&lt;a&gt; <span class="right">(<?=count($value['a']); ?>)</span></th>
                    </tr>
                    <tr>
                        <td style="background-color: #999;"><strong><em>href</em></strong></td>
                        <td style="background-color: #999;"><strong><em>value</em></strong></td>
                        <td style="background-color: #999;"><strong><em>title</em></strong></td>
                        <td style="background-color: #999;"><strong><em>name</em></strong></td>
                    </tr>
<?php foreach ($value['a'] as $a): ?>
                    <tr>
                        <td><?=$a['href']; ?></td>
                        <td><?=$a['value']; ?></td>
                        <td><?=$a['title']; ?></td>
                        <td><?=$a['name']; ?></td>
                    </tr>
<?php endforeach; ?>
                </table>
