                <table class="sub-data-table" cellpadding="0" cellspacing="0" border="0">
                    <tr>
                        <th>&lt;<?=$k; ?>&gt; <span class="right">(<?=count($v); ?>)</span></th>
                    </tr>
<?php foreach ($v as $val): ?>
                    <tr>
                        <td><?=$val; ?></td>
                    </tr>
<?php endforeach; ?>
                </table>
