                <table class="sub-data-table" cellpadding="0" cellspacing="0" border="0">
                    <tr>
                        <th colspan="3">&lt;img&gt; <span class="right">(<?=count($value['img']); ?>)</span></th>
                    </tr>
                    <tr>
                        <td style="background-color: #999;"><strong><em>src</em></strong></td>
                        <td style="background-color: #999;"><strong><em>alt</em></strong></td>
                        <td style="background-color: #999;"><strong><em>title</em></strong></td>
                    </tr>
<?php foreach ($value['img'] as $img): ?>
                    <tr>
                        <td><?=$img['src']; ?></td>
                        <td><?=$img['alt']; ?></td>
                        <td><?=$img['title']; ?></td>
                    </tr>
<?php endforeach; ?>
                </table>
