                <table class="sub-data-table" cellpadding="0" cellspacing="0" border="0">
                    <tr>
                        <th colspan="2">&lt;meta&gt; <span class="right">(<?=count($value['meta']); ?>)</span></th>
                    </tr>
                    <tr>
                        <td style="background-color: #999;"><strong><em>name</em></strong></td>
                        <td style="background-color: #999;"><strong><em>content</em></strong></td>
                    </tr>
<?php foreach ($value['meta'] as $meta): ?>
                    <tr>
                        <td><?=$meta['name']; ?></td>
                        <td><?=$meta['content']; ?></td>
                    </tr>
<?php endforeach; ?>
                </table>
